CREATE TABLE IF NOT EXISTS delivery_feedback (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  order_id BIGINT UNSIGNED NOT NULL,
  seller_sale_id BIGINT UNSIGNED NULL,
  seller_delivery_assignment_id BIGINT UNSIGNED NULL,
  delivery_id BIGINT UNSIGNED NULL,
  seller_id BIGINT UNSIGNED NULL,
  delivery_user_id BIGINT UNSIGNED NOT NULL,
  client_id BIGINT UNSIGNED NOT NULL,
  rating TINYINT UNSIGNED NOT NULL,
  issue_type ENUM(
    'positive',
    'delay',
    'behavior',
    'handover',
    'product_issue',
    'other'
  ) NOT NULL DEFAULT 'other',
  comment VARCHAR(1000) NULL,
  status ENUM('new','in_review','resolved') NOT NULL DEFAULT 'new',
  support_note VARCHAR(500) NULL,
  reviewed_by BIGINT UNSIGNED NULL,
  reviewed_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT chk_delivery_feedback_rating CHECK (rating BETWEEN 1 AND 5),
  UNIQUE KEY unique_delivery_feedback_assignment (client_id,seller_delivery_assignment_id),
  UNIQUE KEY unique_delivery_feedback_delivery (client_id,delivery_id),
  INDEX idx_delivery_feedback_status (status,created_at),
  INDEX idx_delivery_feedback_driver (delivery_user_id,created_at),
  INDEX idx_delivery_feedback_seller (seller_id,created_at),
  INDEX idx_delivery_feedback_order (order_id,created_at),
  FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  FOREIGN KEY (seller_sale_id) REFERENCES seller_sales(id) ON DELETE SET NULL,
  FOREIGN KEY (seller_delivery_assignment_id)
    REFERENCES seller_delivery_assignments(id) ON DELETE CASCADE,
  FOREIGN KEY (delivery_id) REFERENCES deliveries(id) ON DELETE CASCADE,
  FOREIGN KEY (seller_id) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (delivery_user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (client_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL
);
